### ISSUE TITLE
Have you ever tried this out?

### ISSUE THREAD

**Issue by rdbende** [whmsft/pival#1]
@whmsft Just wondering, have you ever tried out this module? 😆

**Comment by whmsft** [comment]
I hope never! 😂

This was my one of the first PyPi modules!
And so it exists..

I just deleted many of my useless repos and archived a few more just yesterday...

**Comment by rdbende** [comment]
It gives an error... Because you're trying to slice a float, that is not possible. ;)

**Comment by whmsft** [comment]
Haha

**Comment by whmsft** [comment]
Out of the 24 repos which are just sitting in my github, I consider only "WhirlEdit" and "popup" to be somewhat good! And rest are all a piece of crap! (there are two more text editors in my github - thee, private; bitedit, not even working a bit!)
